### PR TITLE
Make widgets open so they can be extended

### PR DESCRIPTION
**Pull request by ketankmr**

### CODE REVIEW

**Comment by tfcporciuncula** [comment]
It's not clear to me what this is about. Would you mind adding a screenshot with an example and elaborating more on the issue?

**Comment by ketankmr** [comment]
IMG_20201002_193652
IMG_20201002_193652
Due to left drawable textInputlayout hint moved to the right and is not aligning with the form. So added changes to fix it.

**Comment by tfcporciuncula** [comment]
Oh I see now. This is the default behavior for `TextInputLayout` with a leading icon as you can see [here](https://material.io/components/text-fields#anatomy), so I wouldn't want to go against that in the library -- especially with a solution that involves reflection. I suggest you to open an issue in the [Material Components for Android repo](https://github.com/material-components/material-components-android) so they can add an option to configure that, and then this library would be able to take advantage of it.

**Comment by ketankmr** [comment]
Can u please make the textinputlayout class constructor public so that someone can inherit and make the required changes

**Comment by tfcporciuncula** [comment]
Yeah sure, I'll update the PR title to reflect the final change. Could you please do the same for `PhonemojiFlagTextView`? Just for the sake of consistency.

**Comment by ketankmr** [comment]
Sure

**Comment by tfcporciuncula** [comment]
Actually, I think we want to go with `open` instead of `public`, right?

**Comment by ketankmr** [comment]
yeah will make the changes

**Comment by ketankmr** [comment]
done please check

**Review by tfcporciuncula — APPROVED** [review]

**Pull request merged**
